/**
 * Writes src/environments/environment.deploy.ts from NG_APP_API_URL (Vercel / CI).
 * Example: NG_APP_API_URL=https://committee-api.onrender.com/api
 */
const fs = require('fs');
const path = require('path');

const raw = process.env.NG_APP_API_URL;
if (!raw || !String(raw).trim()) {
  console.error(
    '\n[inject-env] Set NG_APP_API_URL before build.\n' +
      '  Example: https://your-backend-host.com/api\n' +
      '  Vercel: Project → Settings → Environment Variables\n',
  );
  process.exit(1);
}

let base = String(raw).trim().replace(/\/$/, '');
if (!base.endsWith('/api')) {
  base = `${base}/api`;
}

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.deploy.ts');
const content = `/* Auto-generated by scripts/inject-env.cjs — do not edit */
export const environment = {
  production: true,
  apiUrl: ${JSON.stringify(base)},
};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('[inject-env] Wrote', path.relative(process.cwd(), outPath), '→', base);
